version: '3'
services:
  user:
    container_name: user_service
    build: 
      context: ./user_service
      args:
        JDK_VERSION: 17
      dockerfile: Dockerfile
    image: kreshan88/user
    ports:
      - 1234:1234
  department:
    container_name: department_service
    build: 
      context: ./department_service
      dockerfile: Dockerfile
    image: kreshan88/department
    ports:
      - 1235:1235
    links:
      - "user:user_service"