#expose my end point to end user, as a service
apiVersion: v1
kind: Service
metadata:           
  name: cloudetestk-serviceku
spec:  
  type: NodePort           
  ports: 
    - port: 8888
      targetPort: 8081
      protocol: TCP
  selector:
    app: myappku